apiVersion: v1
kind: Service
metadata:
  name: service-hellok8s-nodeport
spec:
  type: NodePort
  selector:
    app: hellok8s
  ports:
  - port: 3001
    nodePort: 32601
    targetPort: 3001	#将请求转发到匹配 Pod 的 3001 端口