---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2021/12/29 15:26
---


a1 = 'hello'
a2 = "hello"
a3 = [[hello]]

print(a1, a2, a3)


-- 常见的字符串操作

str = string.upper("hello")
print("大写转换：", str)
str = string.lower("HELLO")
print("小写转换：",str)

--	string.gsub(mainString,findString,replaceString,num)
-- mainString 为要操作的字符串， findString 为被替换的字符，replaceString 要替换的字符，num 替换次数（可以忽略，则全部替换
data = string.gsub("hello world", "hello", "replace", 1)
print(data)

-- todo string.find(s, pattern [, init [, plain]] )
--[[
    s: 源字符串
    pattern: 待搜索模式串
    init: 可选， 起始位置 正数表示从第几位开始匹配 负数则是从倒数第几位开始匹配
    plain: 默认为false 但是填了这个的话第三个参数也要填
        参数为true函数只默认简单查找子串"%d"，如果你也不确定 find 的字符串会不会包含元字符，靠谱的方式，还是加个 true 参数比较好！
        参数为false时，函数会按模式匹配查找，"%d"表示查找一个数字。
 ]]
num1, num2, str = string.find("hello world", "wo")  -- 查询到 7	8
print("find 方法： ", num1, num2,str)
num1, num2 = string.find("hello world", "你")  -- 未查询到 nil	nil
print(num1, num2)

print(string.find("这是例子%d","%d",1,true))  -- 只是查找字符 %d  13	14
print(string.find("这是例子%d","%d",1,false)) -- 查找的是 %d的正则方式，查找数字  nil
print(string.find("这是13例子%d","%d",1,false)) -- 查找的是 %d的正则方式，查找数字  7	7


-- string.reverse(arg)
print(string.reverse("Lua"))

-- string.format(...)
print(string.format("the value is:%d",4))


-- 	string.char(arg) 和 string.byte(arg[,int])
print(string.char(65,67,68))  -- ACD
print(string.byte("ABCD",1,3)) -- 65	66	67

-- 	string.len(arg)
print(string.len("hello"))

-- 	string.rep(string, n) 返回字符串string的n个拷贝
print(string.rep("hello", 2))


-- .. 链接两个字符串
print("hello".."world")

-- string.match(str, pattern, init)
-- string.match()只寻找源字串str中的第一个配对. 参数init可选, 指定搜寻过程的起点, 默认为1。
print("string.match 正则匹配：", string.match("I have 22 questions for you.", "%d+"))


-- 字符串截取 字符串截取使用 sub() 方法。 string.sub() 用于截取字符串，原型为： string.sub(s, i [, j])
local sourcestr = "prefix--runoobgoogletaobao--suffix"
local first_sub = string.sub(sourcestr, 4, 15)
print("\n第一次截取", string.format("%q", first_sub))
-- 截取最后10个
local third_sub = string.sub(sourcestr, -10)
print("\n第三次截取", string.format("%q", third_sub))