---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2021/12/29 15:26
---


a1 = 'hello'
a2 = "hello"
a3 = [[hello]]

print(a1, a2, a3)


-- 常见的字符串操作

str = string.upper("hello")
print("大写转换：", str)
str = string.lower("HELLO")
print("小写转换：",str)

--	string.gsub(mainString,findString,replaceString,num)
-- mainString 为要操作的字符串， findString 为被替换的字符，replaceString 要替换的字符，num 替换次数（可以忽略，则全部替换
data = string.gsub("hello world", "hello", "replace", 1)
print(data)

-- todo string.find(s, pattern [, init [, plain]] )
--[[
    s: 源字符串
    pattern: 待搜索模式串
    init: 可选， 起始位置 正数表示从第几位开始匹配 负数则是从倒数第几位开始匹配
    plain: 默认为false 但是填了这个的话第三个参数也要填
        参数为true函数只默认简单查找子串"%d"，如果你也不确定 find 的字符串会不会包含元字符，靠谱的方式，还是加个 true 参数比较好！
        参数为false时，函数会按模式匹配查找，"%d"表示查找一个数字。
 ]]
num1, num2, str = string.find("hello world", "wo")  -- 查询到 7	8
print("find 方法： ", num1, num2,str)
num1, num2 = string.find("hello world", "你")  -- 未查询到 nil	nil
print(num1, num2)

print(string.find("这是例子%d","%d",1,true))  -- 只是查找字符 %d  13	14
print(string.find("这是例子%d","%d",1,false)) -- 查找的是 %d的正则方式，查找数字  nil
print(string.find("这是13例子%d","%d",1,false)) -- 查找的是 %d的正则方式，查找数字  7	7


-- string.reverse(arg)
print(string.reverse("Lua"))

-- string.format(...)
--[[
    Lua 提供了 string.format() 函数来生成具有特定格式的字符串, 函数的第一个参数是格式 , 之后是对应格式中每个代号的各种数据。
    由于格式字符串的存在, 使得产生的长字符串可读性大大提高了。这个函数的格式很像 C 语言中的 printf()。
    以下实例演示了如何对字符串进行格式化操作：
    格式字符串可能包含以下的转义码:

    %c - 接受一个数字, 并将其转化为ASCII码表中对应的字符
    %d, %i - 接受一个数字并将其转化为有符号的整数格式
    %o - 接受一个数字并将其转化为八进制数格式
    %u - 接受一个数字并将其转化为无符号整数格式
    %x - 接受一个数字并将其转化为十六进制数格式, 使用小写字母
    %X - 接受一个数字并将其转化为十六进制数格式, 使用大写字母
    %e - 接受一个数字并将其转化为科学记数法格式, 使用小写字母e
    %E - 接受一个数字并将其转化为科学记数法格式, 使用大写字母E
    %f - 接受一个数字并将其转化为浮点数格式
    %g(%G) - 接受一个数字并将其转化为%e(%E, 对应%G)及%f中较短的一种格式
    %q - 接受一个字符串并将其转化为可安全被Lua编译器读入的格式
    %s - 接受一个字符串并按照给定的参数格式化该字符串
    为进一步细化格式, 可以在%号后添加参数. 参数将以如下的顺序读入:

    (1) 符号: 一个+号表示其后的数字转义符将让正数显示正号. 默认情况下只有负数显示符号.
    (2) 占位符: 一个0, 在后面指定了字串宽度时占位用. 不填时的默认占位符是空格.
    (3) 对齐标识: 在指定了字串宽度时, 默认为右对齐, 增加-号可以改为左对齐.
    (4) 宽度数值
    (5) 小数位数/字串裁切: 在宽度数值后增加的小数部分n, 若后接f(浮点数转义符, 如%6.3f)则设定该浮点数的小数只保留n位, 若后接s(字符串转义符, 如%5.3s)则设定该字符串只显示前n位.
]]
print(string.format("the value is:%d",4))
-- 日期格式化
date = 2; month = 1; year = 2014
print(string.format("日期格式化 %02d/%02d/%03d", date, month, year))

-- 	string.char(arg) 和 string.byte(arg[,int])
print(string.char(65,67,68))  -- ACD
print(string.byte("ABCD",1,3)) -- 65	66	67
print("转换第一个字符： ", string.byte("Lua"))

-- 	string.len(arg)
print(string.len("hello"))

-- 	string.rep(string, n) 返回字符串string的n个拷贝
print(string.rep("hello", 2))


-- .. 链接两个字符串
print("hello".."world")

-- string.match(str, pattern, init)
-- string.match()只寻找源字串str中的第一个配对. 参数init可选, 指定搜寻过程的起点, 默认为1。
print("string.match 正则匹配：", string.match("I have 22 questions for you.", "%d+"))


-- 字符串截取 字符串截取使用 sub() 方法。 string.sub() 用于截取字符串，原型为： string.sub(s, i [, j])
local sourcestr = "prefix--runoobgoogletaobao--suffix"
local first_sub = string.sub(sourcestr, 4, 15)
print("\n第一次截取", string.format("%q", first_sub))
-- 截取最后10个
local third_sub = string.sub(sourcestr, -10)
print("\n第三次截取", string.format("%q", third_sub))