---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2021/12/29 21:10
---

--C:\Program Files (x86)\Lua\5.1\lua\


print("-------lua数组---------")

-- 一维数组
-- 一维数组是最简单的数组，其逻辑结构是线性表。一维数组可以用for循环出数组中的元素，如下实例：

arr1 = {"lua", 'tutorial'}
for i, v in pairs(arr1) do
    print(i, v )
end

for i = 0, #arr1 do
    print(arr1[i])  -- 没有的索引值0 返回nil
end


-- 除此外我们还可以以负数为数组索引值：
for i = -2, 2 do
    arr1[i] = i * 2
end

for i = -2, 2 do
   print("遍历负数索引： ", arr1[i])
end


-- 多维数组
arr2 = {}
for i = 1, 3 do
    arr2[i] = {}
    for j = 1, 3 do
        arr2[i][j] = i * j
    end
end
--访问多维数组
for i, v in ipairs(arr2) do
    print("多维数组：", i, v)
    for j, t in ipairs(v) do
        print(j, t)
    end
end

for i = 1, 3 do
    for j = 1, 3 do
        print(arr2[i][j])
    end
end





