---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2022/1/6 16:32
---

file_data = io.open("./test.txt", "r+")

print(file_data)
print(file_data:read())



-- 循环文件内容
for line in file_data:lines() do
    print(line)
end

