---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2021/12/29 12:20
---



function MyMax(num1, num2)
    if num1 > num2 then
         result = num1
    else
        result =  num2
    end
    return result
end


maxNum = MyMax(11,2)
print(maxNum)


-- 多返回值
s, e = string.find("www.baidu.com", "baidu")
print(s, e)



-- 函数作为参数使用

f1 = function(param1, param2)
    print("this is my print function:", param1, " .... ....", param2)
end


function MyJoin(a, b, f1)
    f1(a, b)
end

MyJoin("hello", "world", f1)


-- 可变参数 Lua 函数可以接受可变数目的参数，和 C 语言类似，在函数参数列表中使用三点 ... 表示函数有可变的参数。

function average(...)
    result = 0
    local arg = {...}
    for i, v in ipairs(arg) do
        print(i, v )
        result = result + v
    end
    print("总共传入 " .. #arg .. " 个数")
    return result / #arg
end


print("长度： ", #"hello")
print("长度： ", #{"name", "age"})

avg = average(1,2,3,4,5)
print("平均值： ", avg)


-- 我们也可以通过 select("#",...) 来获取可变参数的数量:

function average2(...)
    result = 0
    local arg = {...}
    for i, v in ipairs(arg) do
        print(i, v)
        result = result + v
    end
    print("select 数量： ", select("#", ...), " =====")
    return result / select("#", ...)
end

avg2 = average2(3,4,4)
print("avg2 : ", avg2)


-- 固定参数加上可变参数
function fWrite(fmt, ...)
    return io.write(string.format(fmt, ...))
end

fWrite("hello\n")

fWrite("%s%s\n", "jack", 'lucy')



function f(...)
    a = select(3,...)  -->从第三个位置开始，变量 a 对应右边变量列表的第一个参数
    print (a)
    print (select(3,...)) -->打印所有列表参数
end

f(0,1,2,3,4,5)
