---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2021/12/29 12:15
---



if false then
    print("this is key true")
else
    print("this is false")
end

if false then
    print("elseif ", "第一层")
elseif false then
    print("elseif ", "第二层")
else
    print("elseif ", "第三层")
end



-- if嵌套

if true then
    print("if 嵌套 ： ", "第一层")
    if true then
        print("if 嵌套 ： ", "第二层")
    end
end