---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2021/12/29 10:03
---


print('-------------lua的变量--------')


--[[
	lua的变量有三种： 全局变量，局部变量，表中的域
	lua中的变量全是全局变量
]]
