---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2021/12/29 22:30
---

print("=======module的导入和使用==========")


--todo 需要配置lua的路径才能生效
--[[
    LUA_PATH=C:\Program Files (x86)\Lua\5.1\?.lua  可以配置ide的环境变量
    然后将文件放到对应的路径下面即可
]]
print(package.path) -- 查看模块的加载路径
-- require 函数
--Lua提供了一个名为require的函数用来加载模块。要加载一个模块，只需要简单地调用就可以了。例如：
local m = require("moduleTest") -- moduleTets 这个是文件的名称 按照保存文件的文件名来的
--方式二
--require "module"
print(m)

print(m.constant)
print(m.func1())
print(m.func2())