---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2021/12/29 11:28
---



print("pairs和ipairs的异同")
--[[
    同：都是能遍历集合（表、数组）
    异：ipairs 仅仅遍历值，按照索引升序遍历，索引中断停止遍历。即不能返回 nil,只能返回数字 0，如果遇到 nil 则退出。它只能遍历到集合中出现的第一个不是整数的 key。
        pairs 能遍历集合的所有元素。即 pairs 可以遍历集合中所有的 key，并且除了迭代器本身以及遍历表本身还可以返回 nil。
]]

local tabFiles = {
    [1] = "test2",
    [6] = "test3",
    [4] = "test1"
}

for i, v in pairs(tabFiles) do
    print("pairs: ", i, v)  --
end

for i, v in ipairs(tabFiles) do  -- 索引中断停止遍历
    print("ipairs: ", i, v)  -- 只循环了第一个 ipairs: 	1	test2 后面就退出了
end



local a = {}
a["name"] = "jack"
a["age"] = 19

for i, v in ipairs(a) do   -- ipairs 没有索引不会循环
    print("没有索引：ipairs: 不会执行循环", i, v)
end

for i, v in pairs(a) do
    print("没有索引 pairs：正常循环 ", i, v)
end


local b ={ -- 初始化table
    a = 1,
    name = "jack"
}

for i, v in pairs(b) do
    print(i, v)
end


