---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2022/9/17 14:52
---




--function Sleep(n)
--    local t0 = os.clock()
--    while os.clock() - t0 <= n do end
--
--end
--
----Sleep(5)
--
--
--function Sleep02(n)
--    if n > 0 then os.execute("ping -n " ..  tonumber(n +1) .. " localhost > NULL" ) end
--end
--
--
--
--Sleep02(5)


a = 10
while (a < 20 ) do
    print("while 循环 。。。", a)
    a = a + 1
end
