---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengwei.
--- DateTime: 2021/12/29 14:52
---


-- 算术运算符
print(" + ", 1+4)
print(" - ", 4-1,  1-3)
print(" * ", 4 * 5)
print(" / ", 4/5)
print(" % 取余 ", 5%3)
print(" ^ ", 2^3)




-- 关系运算符
print("  等于 ", 1 == 1)
print(" 不等于 ", 1 ~= 2)
print("  大于等于 ", 3 >= 2)



-- 逻辑运算符号
print(false and true)  -- 与
print(false or true) -- 或
print(not false)  -- true
print(not nil) -- true
print(not 0)   --false 只有nil为false


-- 其他运算符
--.. 字符串的拼接
-- #字符串或者table的长度
a = "Hello "
b = "World"
print("连接字符串 a 和 b ", a..b )
print("b 字符串长度 ",#b )